apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
